version: "2"
linters:
  default: all
  disable:
    - arangolint
    - exhaustruct
    - gochecknoglobals
    - gomodguard
    - wsl
    - zerologlint
    # - asasalint
    # - asciicheck
    # - bidichk
    # - bodyclose
    # - canonicalheader
    # - clickhouselint
    # - containedctx
    # - contextcheck
    # - copyloopvar
    # - cyclop
    # - decorder
    # - depguard
    # - dogsled
    # - dupl
    # - dupword
    # - durationcheck
    # - embeddedstructfieldcheck
    # - err113
    # - errcheck
    # - errchkjson
    # - errname
    # - errorlint
    # - exhaustive
    # - exhaustruct_v5
    # - exptostd
    # - fatcontext
    # - forbidigo
    # - forcetypeassert
    # - funcorder
    # - funlen
    # - ginkgolinter
    # - gocheckcompilerdirectives
    # - gochecknoinits
    # - gochecksumtype
    # - gocognit
    # - goconst
    # - gocritic
    # - gocyclo
    # - godoclint
    # - godot
    # - godox
    # - goheader
    # - gomoddirectives
    # - gomodguard_v2
    # - goprintffuncname
    # - gosec
    # - gosmopolitan
    # - govet
    # - grouper
    # - iface
    # - importas
    # - inamedparam
    # - ineffassign
    # - interfacebloat
    # - intrange
    # - iotamixing
    # - ireturn
    # - lll
    # - loggercheck
    # - maintidx
    # - makezero
    # - mirror
    # - misspell
    # - mnd
    # - modernize
    # - musttag
    # - nakedret
    # - nestif
    # - nilerr
    # - nilnesserr
    # - nilnil
    # - nlreturn
    # - noctx
    # - noinlineerr
    # - nolintlint
    # - nonamedreturns
    # - nosprintfhostport
    # - paralleltest
    # - perfsprint
    # - prealloc
    # - predeclared
    # - promlinter
    # - protogetter
    # - reassign
    # - recvcheck
    # - revive
    # - rowserrcheck
    # - sloglint
    # - spancheck
    # - sqlclosecheck
    # - staticcheck
    # - tagalign
    # - tagliatelle
    # - testableexamples
    # - testifylint
    # - testpackage
    # - thelper
    # - tparallel
    # - unconvert
    # - unparam
    # - unqueryvet
    # - unused
    # - usestdlibvars
    # - usetesting
    # - varnamelen
    # - wastedassign
    # - whitespace
    # - wrapcheck
    # - wsl_v5
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          # allow:
          #   - 
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/sirupsen/logrus"
              desc: not allowed another logger, use slog
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
    varnamelen:
      max-distance: 5
      min-name-length: 2
      check-receiver: true
      check-return: true
      check-type-param: true
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-names:
        - err
      ignore-decls:
        - i int
        - s string
        - fd *os.File
        # sync
        - wg sync.WaitGroup
        - eg *errgroup.Group
        # http
        - r *http.Request
        - w http.ResponseWriter
  exclusions:
    # Mode of the generated files analysis.
    #
    # - `strict`: sources are excluded by strictly following the Go generated file convention.
    #    Source files that have lines matching only the following regular expression will be excluded: `^// Code generated .* DO NOT EDIT\.$`
    #    This line must appear before the first non-comment, non-blank text in the file.
    #    https://go.dev/s/generatedcode
    # - `lax`: sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc.
    # - `disable`: disable the generated files exclusion.
    #
    # Default: strict
    generated: lax
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      # Run some linter only for test files by excluding its issues for everything else.
      # - path-except: _test\.go
      #   linters:
      #     - forbidigo
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - godoclint
        source: "^// (TODO|BUG|FIXME)"
    # Which file paths to exclude: they will be analyzed, but issues from them won't be reported.
    # "/" will be replaced by the current OS file path separator to properly work on Windows.
    # Default: []
    # paths:
    # - ".*\\.my\\.go$"
    # Which file paths to not exclude.
    # Default: []
    # paths-except:
    # - ".*\\.my\\.go$"
    # - lib/bad.go
formatters:
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/novoseltsev-stan/droid) # Custom section: groups all imports with the specified Prefix.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
      no-lex-order: false
issues:
  max-issues-per-linter: 10
  max-same-issues: 3
  uniq-by-line: false
  new: false
  fix: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
    json:
      path: .reports/golangci-lint.json
  sort-order:
    - severity
    - linter
    - file
  show-stats: true
run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly
  enable-build-vcs: true
  allow-parallel-runners: true
  allow-serial-runners: true
  concurrency: 0
severity:
  default: error
  rules:
    - linters:
        - dupl
        - godox
        - varnamelen
      severity: info
